version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: