"""add datatime in user

Revision ID: 2ccc3e74cdce
Revises: f051f59a4f81
Create Date: 2025-02-18 08:37:28.556214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccc3e74cdce'
down_revision: Union[str, None] = 'f051f59a4f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_updated')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
